server:
  address: 0.0.0.0
  port: 8080
python:
  render:
    url: http://localhost:4000/render
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/builder}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
  security:
    enabled: true  # ← ВКЛЮЧАЕТ Spring Security
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  packages-to-scan: com.example.builder.landingbuilder.controller
